server:
  port: 8887
spring:
  cloud:
    config:
      server:
        git:
          uri: D:\ideaworkspace\spring-cloud-test
#          uri: D:\ideaworkspace\spring-config-demo
          searchPaths: config