server:
  port: 6375   # 注册服务的端口号
spring:
  application:
    name: redis-server
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/spring-cloud-test
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      min-idle: 5
      max-active: 20
      filters: stat,wall,log4j #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据
      #打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
  jedis:
    pool:
      host: 127.0.0.1
      port: 6379
      config :
        maxTotal: 100
        maxIdle: 10
        maxWaitMillis : 100000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

